---

- name: Hostname | Update FQDN hostname
  hostname:
    name: "{{ hostname__fqdn }}"

- name: Hostname | Update hosts File
  template:
    src: hosts.j2
    dest: "{{ hostname__host_file }}"
    owner: root
    group: root
    mode: 0644
